server:
  build: .
  ports:
    - "80:80"
    - "443:443"
    - "3000:3000"
  volumes:
  - "server:/src"
  command: sh -c "node server.js & nginx -g 'daemon off;'"
  environment:
      NODE_ENV: trunk
  restart: always

